exporting gpg key

diff --git a/source/build/build/create-secure-apt-repository b/source/build/build/create-secure-apt-repository
--- a/source/build/build/create-secure-apt-repository
+++ b/source/build/build/create-secure-apt-repository
@@ -76,6 +76,8 @@ function setPaths()
 	readonly packageTemplatesPath="$sourcePath"/build/package-templates
 	readonly keyringsPath="$packageTemplatesPath"/hdn-keyring-private/hdn-keyring-private/etc/hdn-keyring-private
 	readonly keyringPath="$keyringsPath"/"$keyring"
+	readonly repositoryKey="$archiveDirPath"/"$repositoryName".key
+	readonly installFilePath="$archiveDirPath"/"$repositoryName".sh
 }
 
 function makePaths()
@@ -215,9 +217,92 @@ function generateSourceListSnippets()
 function exportPublicKey()
 {
 	gpgWrapped --list-keys
-	gpgWrapped --export --armor >"$archiveDirPath"/"$codeName".key
+	gpgWrapped --export --armor >"$repositoryKey"
 	# gpgWrapped --export B1850655 | sudo -p "Password to install signing key" apt-key add -
 	:
+	
+	# Write a script that installs this key and apt sources...
+	cat <<-EOF >"$installFilePath"
+		#!/bin/bash -
+		
+		# © Crown Copyright 2013
+		#
+		# Licensed under the Apache License, Version 2.0 (the "License");
+		# you may not use this file except in compliance with the License.
+		# You may obtain a copy of the License at
+		#
+		#     http://www.apache.org/licenses/LICENSE-2.0
+		#
+		# Unless required by applicable law or agreed to in writing, software
+		# distributed under the License is distributed on an "AS IS" BASIS,
+		# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+		# See the License for the specific language governing permissions and
+		# limitations under the License.
+		
+		set -e
+		
+		readonly ourName="$(basename "$0")"
+		
+		cd "$(dirname "$0")" 1>/dev/null
+		readonly crudeOurPath="$(pwd)"
+		cd - 1>/dev/null
+		
+		function exitHelp()
+		{
+			echo "Usage: $ourName [--help]" 1>&2
+			exit $1
+		}
+		
+		function exitError()
+		{
+			local -r error="$1"
+			echo "$ourName: $error" 1>&2
+			exitHelp 1
+		}
+		
+		function parseCommandLine()
+		{
+			if [ $# -eq 0 ]; then
+				:
+			elif [ $# -eq 1 ]; then
+				if [ "$1" = "--help" ]; then
+					exitHelp 2
+				elif  [ "$1" = "-h" ]; then
+					exitHelp 2
+				else
+					exitError "Invalid options"
+				fi
+			else
+				exitError "Invalid options"
+			fi
+		}
+		
+		function importKey()
+		{
+			cat <<-EOK | sudo -p "Password to import key for repository $repositoryName: " apt-key import -
+				$(cat ${repositoryKey})
+			EOK
+		}
+		
+		function createSourcesListFragment()
+		{
+			cat <<-EOK >/etc/apt/sources.list.d/00hdn.secure.http.sources.list
+				deb http://$(hostname).cloudapp.net/archives/${repositoryName}/ ${codeName} ${sectionNames}
+				deb-src http://$(hostname).cloudapp.net/archives/${repositoryName}/ ${codeName} ${sectionNames}
+			EOK
+		}
+		
+		function main()
+		{
+			parseCommandLine "$@"
+			importKey
+			createSourcesListFragment
+		}
+		
+		main "$@"
+	EOF
+	
+	chmod +x "$installFilePath"
 }
 
 function parseCommandLine()
